routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

// Route::get('/', function () {
//     return view('auth2.login');
// });

Auth::routes();

Route::resource('house', 'HouseUnitController');
Route::resource('tenant', 'TenantController');
Route::resource('userdetail', 'UserDetailsController');

Route::resource('userlevel', 'UserlevelController');

app/Tenant.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Tenant extends Model
{
    use SoftDeletes;
    
    public function houseunits() {
        return $this->belongsTo('App\HouseUnit', 'house_id');
    }
}

app/Http/Controllers/TenantController.php
<?php

namespace App\Http\Controllers;

use App\Tenant;
use Auth;
use App\HouseUnit;
use App\User;
use App\userDetails;
use Illuminate\Http\Request;
use App\Userlevel;
use Illuminate\Support\Facades\Gate;

class TenantController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(Gate::allows('admin-only', Auth::user()->userlevel->userLevel))
        {
            $userA=Tenant::all();
            $i=1;
            return view('tenant.list', compact('userA', 'i'));
        }
        $houses=HouseUnit::where('owner_id', '=', Auth::user()->id)->pluck('id')->toArray();
        $userA=Tenant::wherein('house_id', $houses)->get();
        // dd($userA);
        $i=1;
        return view('tenant.list', compact('userA', 'i'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Gate::allows('admin-only', Auth::user()->userlevel->userLevel)){
            $houses=HouseUnit::all();
            return view('tenant.create', compact('houses'));
        }
        $houses=HouseUnit::where('owner_id', '=', Auth::User()->id)->get();
        return view('tenant.create', compact('houses'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $id = $this->separate($request);
        
        if(Gate::allows('admin-only', Auth::user()->userlevel->userLevel)||$this->checkExist($request)||$id[1]==Auth::User()->id)
        {
            $tenant= new Tenant();
            $tenant->name=$request->get('name');
            $tenant->passport=$request->get('passport');
            $tenant->citizenship=$request->get('citizen');
            $tenant->phone=$request->get('phone');
            $tenant->duration=$request->get('duration');

            if($request->get('status')==1)
            {
                $house=HouseUnit::find($request->get('houseid'));
                $house->status=1;
                $house->save();
                $tenant->houseunits()->associate($house);
                $tenant->save();
                return redirect('/tenant')->with('success', 'Tenant Registered');
            }

            $house=HouseUnit::find($id[0]);
            $house->status=1;
            $house->save();
            $tenant->houseunits()->associate($house);
            $tenant->save();

            return redirect('/tenant')->with('success', 'Tenant Registered');


        }else
        {
            return redirect('/house')->with('danger', 'Please Contact Admin first');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Tenant  $tenant
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $tenant=Tenant::with('houseunits.user')->where('house_id', '=', $id)->first();
        
        // dd($tenant);
        return view('tenant.show', compact('tenant'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Tenant  $tenant
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
        $tenant=Tenant::with('houseunits')->where('id', '=', $id)->first();
        $houses=HouseUnit::where('owner_id', '=', Auth::User()->id)->get();
        
        // dd($tenant);
        return view('tenant.edit', compact('tenant', 'houses'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Tenant  $tenant
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $tenant=Tenant::find($id);

        // $request->validate([
        //     'name' => 'required | max:1',
        //     'email' => 'required | email',
        //     'department_id' => 'required'
        // ]);

        // $request->validate();

        $id=$this->separate($request);

        $tenant->passport=$request->get('passport');
        $tenant->name=$request->get('name');
        $tenant->phone=$request->get('phone');
        $tenant->duration=$request->get('duration');
        $tenant->citizenship=$request->get('citizen');
        $house=HouseUnit::find($id[0]);
        $tenant->houseunits()->associate($house);
        $tenant->save();



        

        return redirect('/tenant')->with('success', 'Tenant has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Tenant  $tenant
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tenant=Tenant::with('houseunits')->find($id);
        $tenant->houseunits['status']=0;
        $tenant->houseunits->save();

        $tenant->delete();
        return redirect('/tenant')->with('success', 'Tenant has been removed');
    }
    public function checkExist(Request $request)
    {
        if($request->exists('owner')){
            return true;
        }
        return false;
    }
    public function separate(Request $request)
    {
        $id=explode('|', $request->get('status'));
        return $id;
    }
}

resources/views/tenant/create.blade.php
@extends('main.layout')

@section('bootstrap')
<link rel="stylesheet" href="/assets/vendor/bootstrap/css/bootstrap.min.css">
    <link href="/assets/vendor/fonts/circular-std/style.css" rel="stylesheet">
    <link rel="stylesheet" href="/assets/libs/css/style.css">
    <link rel="stylesheet" href="/assets/vendor/fonts/fontawesome/css/fontawesome-all.css">
@endsection

@section('wrapper')
<div class="dashboard-wrapper">
        <div class="container-fluid  dashboard-content">
         
                <div class="row">
                        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                            <div class="page-header">
                                <h2 class="pageheader-title">Register New Tenant</h2>
                                <div class="page-breadcrumb">
                                    <nav aria-label="breadcrumb">
                                        <ol class="breadcrumb">
                                        </ol>
                                    </nav>
                                </div>
                            </div>
                        </div>
                </div>
                <div class="row">
                    <!-- ============================================================== -->
                    <!-- basic form -->
                    <!-- ============================================================== -->
                    <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12">
                        <div class="card">
                               <h5 class="card-header">Tenant Details!</h5>
                               @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>@foreach($errors->all() as $error)
                                        <li>{{ $error  }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                                @endif
                            <div class="card-body">
                                <form method="POST" action="{{ route('tenant.store') }}" id="basicform" data-parsley-validate="">
                                    @csrf
                                    <div class="form-group">
                                        <label for="fn">Full Name</label>
                                        <input id="fn" name="name" type="text" placeholder="Full Name.." class="form-control">
                                    </div>
                                    <div class="form-group">
                                            <label for="pass">IC/Passport</label>
                                            <input id="pass" name="passport" type="text" placeholder="IC/Passport.." class="form-control">
                                        </div>
                                    <div class="form-group">
                                        <label for="c">Citizen</label>
                                        <input id="c" name="citizen" type="text" placeholder="Citizen.." class="form-control">
                                    </div>
                                    <div class="form-group">
                                            <label for="p">Phone</label>
                                            <input id="p" name="phone" type="text" placeholder="Phone.." class="form-control">
                                    </div>
                                    <div class="form-group">
                                            <label for="d">Duration</label>
                                            <input id="d" name="duration" type="text" placeholder="Days.." class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label class="mr-sm-2" for="inlineFormCustomSelect">House</label>
                                        <select name="status" class="custom-select mr-sm-2" id="inlineFormCustomSelect" required>
                                        <option value="" selected>---House---</option>
                                        @foreach ($houses as $h)
                                            <option value="{{$h->id}}|{{$h->owner_id}}">{{$h->block}}-{{$h->level}}-{{$h->housenumber }}</option>
                                        @endforeach
                                        </select>
                                    </div>                                   
                                    <div class="col-sm-6 pl-0">
                                        <p class="text-right">
                                            <button type="submit" class="btn btn-space btn-primary">Submit</button>
                                            <button class="btn btn-space btn-secondary"><a href="{{route('house.index')}}">Cancel</a></button>
                                        </p>
                                    </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <!-- ============================================================== -->
                    <!-- end basic form -->
                    <!-- ============================================================== -->
                </div>
       
        </div>
@endsection

@section('javascript')
<script src="/assets/vendor/jquery/jquery-3.3.1.min.js"></script>
    <script src="/assets/vendor/bootstrap/js/bootstrap.bundle.js"></script>
    <script src="/assets/vendor/slimscroll/jquery.slimscroll.js"></script>
    <script src="/assets/vendor/parsley/parsley.js"></script>
    <script src="/assets/libs/js/main-js.js"></script>
    <script>
    $('#form').parsley();
    </script>
    <script>
    // Example starter JavaScript for disabling form submissions if there are invalid fields
    (function() {
        'use strict';
        window.addEventListener('load', function() {
            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            var forms = document.getElementsByClassName('needs-validation');
            // Loop over them and prevent submission
            var validation = Array.prototype.filter.call(forms, function(form) {
                form.addEventListener('submit', function(event) {
                    if (form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                    }
                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    })();
    </script>
@endsection

{{-- @extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            
            <h1 class="display-3">Update User</h1>
            <form method="POST" action="{{ route('userdetail.update', $userD->id) }}">
            @csrf
            @method('PATCH')
                <div class="row">
                    <div class="col-sn-12">
                        <div class="card">
                            <div class="card-header bg-default">
                                <h2>User: {{$userD->user['name'] }}</h2>
                            </div>
                            <div class="card-body">
                                    @if ($errors->any())
                                    <div class="alert-danger">
                                        <ul>@foreach($errors->all() as $error)
                                            <li>{{ $error  }}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                    @endif
                                <dl class="row">

                                    <dt class="col-sm-3">Name</dt>
                                    <dd class="col-sm-9"><input type="text" name="name" value="{{$userD->user['name']}}" size="50"></dd>
                                    
                                    <dt class="col-sm-3">IC/Passport</dt>
                                    <dd class="col-sm-9"><input type="text" name="passport" value="{{$userD->user['passport']}}" size="50"></dd>
                                    
                                    <dt class="col-sm-3">Citizenship</dt>
                                    <dd class="col-sm-9"><input type="text" name="citizenship" value="{{ $userD->citizenship }}" size="50"></dd>
                                    
                                    <dt class="col-sm-3">Phone</dt>
                                    <dd class="col-sm-9"><input type="text" name="phone" value="{{ $userD->phone }}" size="50"></dd>
        
                                    <dt class="col-sm-3">Email</dt>
                                    <dd class="col-sm-9"><input type="text" name="email" value="{{$userD->email}}" size="50"></dd>

                                </dl>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sn-12 text-center">
                        <button type="submit" class="btn btn-primary">Update changes</button>
                        <a class="btn btn-warning" href="{{route('house.index')}}">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
    
@endsection --}}

resources/views/tenant/edit.blade.php
@extends('main.layout')

@section('bootstrap')
<link rel="stylesheet" href="/assets/vendor/bootstrap/css/bootstrap.min.css">
    <link href="/assets/vendor/fonts/circular-std/style.css" rel="stylesheet">
    <link rel="stylesheet" href="/assets/libs/css/style.css">
    <link rel="stylesheet" href="/assets/vendor/fonts/fontawesome/css/fontawesome-all.css">
@endsection

@section('wrapper')
<div class="dashboard-wrapper">
        <div class="container-fluid  dashboard-content">
         
                <div class="row">
                        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                            <div class="page-header">
                                <h2 class="pageheader-title">Edit Tenant Details</h2>
                                <div class="page-breadcrumb">
                                    <nav aria-label="breadcrumb">
                                        <ol class="breadcrumb">
                                        </ol>
                                    </nav>
                                </div>
                            </div>
                        </div>
                </div>
                <div class="row">
                    <!-- ============================================================== -->
                    <!-- basic form -->
                    <!-- ============================================================== -->
                    <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12">
                        <div class="card">
                               <h5 class="card-header">{{$tenant->name}} Details!</h5>
                               @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>@foreach($errors->all() as $error)
                                        <li>{{ $error  }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                                @endif
                            <div class="card-body">
                                <form method="POST" action="{{ route('tenant.update', $tenant->id) }}" id="basicform" data-parsley-validate="">
                                    @csrf
                                    @method('PATCH')
                                    <div class="form-group">
                                        <label for="fn">Full Name</label>
                                        <input id="fn" name="name" type="text" value="{{$tenant->name}}" class="form-control">
                                    </div>
                                    <div class="form-group">
                                            <label for="pass">IC/Passport</label>
                                            <input id="pass" name="passport" type="text" value="{{$tenant->passport}}" class="form-control">
                                        </div>
                                    <div class="form-group">
                                        <label for="c">Citizen</label>
                                        <input id="c" name="citizen" type="text" value="{{$tenant->citizenship}}" class="form-control">
                                    </div>
                                    <div class="form-group">
                                            <label for="p">Phone</label>
                                            <input id="p" name="phone" type="text" value="{{$tenant->phone}}" class="form-control">
                                    </div>
                                    <div class="form-group">
                                            <label for="d">Duration</label>
                                            <input id="d" name="duration" type="text" value="{{$tenant->duration}}" class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label class="mr-sm-2" for="inlineFormCustomSelect">Houses</label>
                                        <select name="status" class="custom-select mr-sm-2" id="inlineFormCustomSelect" required>
                                        <option value="">---Houses---</option>
                                        @foreach ($houses->where('id', $tenant->house_id) as $h)
                                            <option value="{{$h->id}}|{{$h->owner_id}}" selected>{{$h->block}}-{{$h->level}}-{{$h->housenumber }}</option>
                                        @endforeach
                                        @foreach ($houses->where('id', '!=', $tenant->house_id) as $h)
                                            <option value="{{$h->id}}|{{$h->owner_id}}">{{$h->block}}-{{$h->level}}-{{$h->housenumber }}</option>
                                        @endforeach
                                        </select>
                                    </div>                                   
                                    <div class="col-sm-6 pl-0">
                                        <p class="text-right">
                                            <button type="submit" class="btn btn-space btn-primary">Submit</button>
                                            <button class="btn btn-space btn-secondary"><a href="{{route('house.index')}}">Cancel</a></button>
                                        </p>
                                    </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <!-- ============================================================== -->
                    <!-- end basic form -->
                    <!-- ============================================================== -->
                </div>
       
        </div>
@endsection

@section('javascript')
<script src="/assets/vendor/jquery/jquery-3.3.1.min.js"></script>
    <script src="/assets/vendor/bootstrap/js/bootstrap.bundle.js"></script>
    <script src="/assets/vendor/slimscroll/jquery.slimscroll.js"></script>
    <script src="/assets/vendor/parsley/parsley.js"></script>
    <script src="/assets/libs/js/main-js.js"></script>
    <script>
    $('#form').parsley();
    </script>
    <script>
    // Example starter JavaScript for disabling form submissions if there are invalid fields
    (function() {
        'use strict';
        window.addEventListener('load', function() {
            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            var forms = document.getElementsByClassName('needs-validation');
            // Loop over them and prevent submission
            var validation = Array.prototype.filter.call(forms, function(form) {
                form.addEventListener('submit', function(event) {
                    if (form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                    }
                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    })();
    </script>
@endsection

{{-- @extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            
            <h1 class="display-3">Update User</h1>
            <form method="POST" action="{{ route('tenant.update', $tenant->id) }}">
            @csrf
            @method('PATCH')
                <div class="row">
                    <div class="col-sn-12">
                        <div class="card">
                            <div class="card-header bg-default">
                                <h2>User: {{$tenant->name }}</h2>
                            </div>
                            <div class="card-body">
                                    @if ($errors->any())
                                    <div class="alert-danger">
                                        <ul>@foreach($errors->all() as $error)
                                            <li>{{ $error  }}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                    @endif
                                <dl class="row">

                                    <dt class="col-sm-3">Name</dt>
                                    <dd class="col-sm-9"><input type="text" name="name" value="{{$tenant->name}}" size="50"></dd>
                                    
                                    <dt class="col-sm-3">IC/Passport</dt>
                                    <dd class="col-sm-9"><input type="text" name="passport" value="{{$tenant->passport}}" size="50"></dd>
                                    
                                    <dt class="col-sm-3">Citizenship</dt>
                                    <dd class="col-sm-9"><input type="text" name="citizenship" value="{{ $tenant->citizenship }}" size="50"></dd>
                                    
                                    <dt class="col-sm-3">Phone</dt>
                                    <dd class="col-sm-9"><input type="text" name="phone" value="{{ $tenant->phone }}" size="50"></dd>
        
                                    <dt class="col-sm-3">Duration</dt>
                                    <dd class="col-sm-9"><input type="text" name="duration" value="{{$tenant->duration}}" size="50"></dd>

                                </dl>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sn-12 text-center">
                        <button type="submit" class="btn btn-primary">Update changes</button>
                        <a class="btn btn-warning" href="{{route('house.index')}}">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
    
@endsection --}}

resources/views/tenant/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            
            <h1 class="display-3">Tenant Details</h1>
            <div class="row">
                <div class="card">
                    <div class="card-header bg-default">
                        <h2> Tenant: {{$tenant->name}}</h2>
                    </div>
                    <div class="card-body">
                        <dl class="row">
                            <dt class="col-sm-3">Name</dt>
                            <dd class="col-sm-9">{{$tenant->name}}</dd>
                            
                            <dt class="col-sm-3">IC/Passport</dt>
                            <dd class="col-sm-9">{{$tenant->passport}}</dd>
                            
                            <dt class="col-sm-3">Citizenship</dt>
                            <dd class="col-sm-9">{{ $tenant->citizenship }}</dd>
                            
                            <dt class="col-sm-3">Phone</dt>
                            <dd class="col-sm-9">{{$tenant->phone}}</dd>

                            <dt class="col-sm-3">Duration</dt>
                            <dd class="col-sm-9">{{$tenant->duration}} Days</dd>

                            <dt class="col-sm-3">Rented on:</dt>
                            <dd class="col-sm-9">{{$tenant->created_at}}</dd>

                            <a href="{{route('tenant.edit', $tenant->id)}}" class="btn btn-primary">edit</a>
                        </dl>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-8 offset-sm-2">
            
                <h1 class="display-7">Rented Unit Details</h1>
                <div class="row">
                    <div class="card">
                        <div class="card-header bg-default">
                            <h5> Owner: {{$tenant->houseunits->user['name']}}</h5>
                        </div>
                        <div class="card-body">
                            <dl class="row">
                                <dt class="col-sm-3">Owner</dt>
                                <dd class="col-sm-9">{{$tenant->houseunits->user['name']}}</dd>
                                
                                <dt class="col-sm-3">House Number</dt>
                                <dd class="col-sm-9">{{$tenant->houseunits['housenumber']}}</dd>
                                
                                <dt class="col-sm-3">Level</dt>
                                <dd class="col-sm-9">{{$tenant->houseunits['level']}}</dd>
                                
                                <dt class="col-sm-3">Block</dt>
                                <dd class="col-sm-9">{{$tenant->houseunits['block']}}</dd>
                            </dl>
                        </div>
                    </div>
                </div>
            </div>
    </div>
    
@endsection